## Date: 2024-04-10

In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

In [2]:
s = pd.Series([1, 2, 3, 4, 5, ])

In [3]:
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [4]:
print(s[2])


3


In [6]:
# Create a Series with custom indices
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s)


a    1
b    2
c    3
d    4
e    5
dtype: int64


In [8]:
s = pd.Series({'a': 1, 'b': 2, 'c': 3})
print(s)

a    1
b    2
c    3
dtype: int64


In [9]:
print(s[0])

1


/var/folders/xx/d79nkfh96599rt77ggvv_yg80000gn/T/ipykernel_48213/287792665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [10]:
print(s['a'])


1


In [12]:
# Create a DataFrame from a dictionary
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Chris'],
    'Age': [25, 30, 35],
    'Occupation': ['Engineer', 'Doctor', 'Artist']
})
df

Name  Age Occupation
0  Alice   25   Engineer
1    Bob   30     Doctor
2  Chris   35     Artist

In [13]:
print(df['Name'])

0    Alice
1      Bob
2    Chris
Name: Name, dtype: object


In [14]:
print(df.loc[0])  # Access by label
print(df.iloc[0])  # Access by index

Name             Alice
Age                 25
Occupation    Engineer
Name: 0, dtype: object
Name             Alice
Age                 25
Occupation    Engineer
Name: 0, dtype: object


In [15]:
print(df.iloc[0])

Name             Alice
Age                 25
Occupation    Engineer
Name: 0, dtype: object


In [16]:
print(df.iloc[0])

Name             Alice
Age                 25
Occupation    Engineer
Name: 0, dtype: object


In [18]:
# Get rows where Age is greater than 28
filtered_data = df[df['Age'] > 28]
print(filtered_data)
filtered_data

    Name  Age Occupation
1    Bob   30     Doctor
2  Chris   35     Artist


Name  Age Occupation
1    Bob   30     Doctor
2  Chris   35     Artist

In [20]:
df['Salary'] = [70000, 80000, 90000]
print(df)
df

    Name  Age Occupation  Salary
0  Alice   25   Engineer   70000
1    Bob   30     Doctor   80000
2  Chris   35     Artist   90000


Name  Age Occupation  Salary
0  Alice   25   Engineer   70000
1    Bob   30     Doctor   80000
2  Chris   35     Artist   90000

In [24]:
df['Age'][0] = 56
dfdf = pd.read_csv('data.csv')

/var/folders/xx/d79nkfh96599rt77ggvv_yg80000gn/T/ipykernel_48213/3044647487.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'][0] = 56


Name  Age Occupation
0  Alice   56   Engineer
1    Bob   30     Doctor
2  Chris   35     Artist

In [ ]:
# Reading a csv file
#df = pd.read_csv('data.csv')

In [25]:
# get an overview of data
print(df.describe())

             Age
count   3.000000
mean   40.333333
std    13.796135
min    30.000000
25%    32.500000
50%    35.000000
75%    45.500000
max    56.000000


In [29]:
# Spotify dataset
import pandas as pd

# Load the dataset
df = pd.read_csv('Most_Streamed_Spotify_Songs_2023_Dataset.csv')

# Show the first 5 rows
print(df.head())

                            track_name    artist(s)_name  artist_count  \
0  Seven (feat. Latto) (Explicit Ver.)  Latto, Jung Kook             2   
1                                 LALA       Myke Towers             1   
2                              vampire    Olivia Rodrigo             1   
3                         Cruel Summer      Taylor Swift             1   
4                       WHERE SHE GOES         Bad Bunny             1   

   released_year  released_month  released_day  in_spotify_playlists  \
0           2023               7            14                   553   
1           2023               3            23                  1474   
2           2023               6            30                  1397   
3           2019               8            23                  7858   
4           2023               5            18                  3133   

   in_spotify_charts    streams  in_apple_playlists  ...  bpm key   mode  \
0                147  141381703               

In [30]:
df.describe()


artist_count  released_year  released_month  released_day  \
count    953.000000     953.000000      953.000000    953.000000   
mean       1.556139    2018.238195        6.033578     13.930745   
std        0.893044      11.116218        3.566435      9.201949   
min        1.000000    1930.000000        1.000000      1.000000   
25%        1.000000    2020.000000        3.000000      6.000000   
50%        1.000000    2022.000000        6.000000     13.000000   
75%        2.000000    2022.000000        9.000000     22.000000   
max        8.000000    2023.000000       12.000000     31.000000   

       in_spotify_playlists  in_spotify_charts  in_apple_playlists  \
count            953.000000         953.000000          953.000000   
mean            5200.124869          12.009444           67.812172   
std             7897.608990          19.575992           86.441493   
min               31.000000           0.000000            0.000000   
25%              875.000000           0.000000           13.000000   
50%             2224.000000           3.000000           34.000000   
75%             5542.000000          16.000000           88.000000   
max            52898.000000         147.000000          672.000000   

       in_apple_charts  in_deezer_charts         bpm  danceability_%  \
count       953.000000        953.000000  953.000000       953.00000   
mean         51.908709          2.666317  122.540399        66.96957   
std          50.630241          6.035599   28.057802        14.63061   
min           0.000000          0.000000   65.000000        23.00000   
25%           7.000000          0.000000  100.000000        57.00000   
50%          38.000000          0.000000  121.000000        69.00000   
75%          87.000000          2.000000  140.000000        78.00000   
max         275.000000         58.000000  206.000000        96.00000   

        valence_%    energy_%  acousticness_%  instrumentalness_%  liveness_%  \
count  953.000000  953.000000      953.000000          953.000000  953.000000   
mean    51.431270   64.279119       27.057712            1.581322   18.213012   
std     23.480632   16.550526       25.996077            8.409800   13.711223   
min      4.000000    9.000000        0.000000            0.000000    3.000000   
25%     32.000000   53.000000        6.000000            0.000000   10.000000   
50%     51.000000   66.000000       18.000000            0.000000   12.000000   
75%     70.000000   77.000000       43.000000            0.000000   24.000000   
max     97.000000   97.000000       97.000000           91.000000   97.000000   

       speechiness_%  
count     953.000000  
mean       10.131165  
std         9.912888  
min         2.000000  
25%         4.000000  
50%         6.000000  
75%        11.000000  
max        64.000000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64 
 3   released_year         953 non-null    int64 
 4   released_month        953 non-null    int64 
 5   released_day          953 non-null    int64 
 6   in_spotify_playlists  953 non-null    int64 
 7   in_spotify_charts     953 non-null    int64 
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64 
 10  in_apple_charts       953 non-null    int64 
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64 
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64 
 15  key                   858 non-null    ob

In [38]:
# drop a row
df = df.drop(574)

KeyError: '[574] not found in axis'

In [43]:


# Convert string to integer
#df["streams"] = pd.to_numeric(df["streams"])
df['streams_float'] = df['streams'].astype(float)

filtered_songs = df[df['streams_float'] > 1_000_000_000]

# Show the filtered songs
print(filtered_songs)

                   track_name     artist(s)_name  artist_count  released_year  \
12                    Flowers        Miley Cyrus             1           2023   
14                  As It Was       Harry Styles             1           2022   
15                  Kill Bill                SZA             1           2022   
22           I Wanna Be Yours     Arctic Monkeys             1           2013   
37                Blank Space       Taylor Swift             1           2014   
..                        ...                ...           ...            ...   
790                  Callaita   Bad Bunny, Tainy             2           2019   
820                      Iris  The Goo Goo Dolls             1           1998   
856  SLOW DANCING IN THE DARK               Joji             1           2018   
871       Sweet Child O' Mine      Guns N' Roses             1           1987   
910             The Scientist           Coldplay             1           2002   

     released_month  releas

In [45]:
top_danceable_songs = df.sort_values('danceability_%', ascending=False).head(5)
print(top_danceable_songs)

              track_name           artist(s)_name  artist_count  \
595                 Peru  Ed Sheeran, Fireboy DML             2   
224              Players                Coi Leray             1   
250  The Real Slim Shady                   Eminem             1   
423    Super Freaky Girl              Nicki Minaj             1   
702            Starlight                     Dave             1   

     released_year  released_month  released_day  in_spotify_playlists  \
595           2021              12            23                  2999   
224           2022              11            30                  4096   
250           2000               1             1                 20763   
423           2022               8            12                  4827   
702           2022               3             3                  1856   

     in_spotify_charts     streams  in_apple_playlists  ...   mode  \
595                  0   261286503                  60  ...  Minor   
224         

In [46]:
# Calculate the average BPM by artist
avg_bpm_by_artist = df.groupby('artist(s)_name')['bpm'].mean()

# Show the result
avg_bpm_by_artist

artist(s)_name
(G)I-DLE                                         133.0
21 Savage, Gunna                                 148.0
24kgoldn, Iann Dior                               91.0
50 Cent                                           90.0
A$AP Rocky, Metro Boomin, Roisee                  90.0
                                                 ...  
j-hope                                            97.0
j-hope, J. Cole                                   94.0
sped up 8282                                     144.0
sped up nightcore, ARIZONATEARS, Lil Uzi Vert    130.0
teto                                             119.0
Name: bpm, Length: 644, dtype: float64

In [47]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [49]:
#Import numpy
import numpy as np


In [50]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [51]:
# Shape of the array
print(a.shape)  # Output: (3,)

# Data type of the array
print(a.dtype)  # Output: int64

(3,)
int64


In [52]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print(a + b)  # Output: [5 7 9]
# Multiplication
print(a * 2)  # Output: [2 4 6]

[5 7 9]
[2 4 6]


In [54]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [55]:
#Square root
a = np.array([1, 2, 3])

# Square root
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


In [56]:
a = np.array([1, 2, 3])
b = 2

# Broadcasting
print(a * b)  # Output: [2 4 6]

[2 4 6]


In [57]:
# Slicing an array
a = np.array([1, 2, 3, 4, 5])
print(a[1:4])  # Output: [2 3 4]

[2 3 4]


In [59]:
#Importing and Exporting Data
# Save an array to a text file
np.savetxt('array.txt', a)

# Load data from a text file
b = np.loadtxt('array.txt')